b_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from b_shop import settings
from shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

cart/urls.py
from django.urls import path, re_path

from . import views
from .views import *

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:post_id>', views.cart_add, name='cart_add'),
    path('remove/<int:post_id>', views.cart_remove, name='cart_remove'),
    ]

orders/urls.py
from django.urls import path, re_path

from . import views
from .views import *

urlpatterns = [
    path('create', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Item
from .cart import Cart
from .forms import CartAddItemForm

@require_POST
def cart_add(request, post_id):
    cart = Cart(request)
    post = get_object_or_404(Item, id=post_id)
    form = CartAddItemForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(post=post,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, post_id):
    cart = Cart(request)
    post = get_object_or_404(Item, id=post_id)
    cart.remove(post)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
<!--Body Content-->

    <div id="page-content">
        <div class="bredcrumbWrap">
                    <div class="container breadcrumbs">
                        <a href="/" title="Back to the home page">Каталог</a><span aria-hidden="true">›</span><span>Ваша корзина</span>
                    </div>
                </div>
    	<!--Page Title-->
        <!--End Page Title-->

        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-8 col-lg-8 main-col">
                	<form action="#" method="post" class="cart style2">
                		<table>
                            <thead class="cart__row cart__header">
                                <tr>
                                    <th colspan="2" class="text-right" style=""></th>
                                    <th class="text-left">Цена за ед.</th>
                                    <th class="text-center">Кол-во</th>
                                    <th class="text-right">Всего</th>
                                    <th class="action">&nbsp;</th>
                                </tr>
                            </thead>
                    		<tbody>
                    {% for items in cart %}
                         {% with post=items.item %}
                                <tr class="cart__row border-bottom line1 cart-flex border-top">
                                    {% with variable=post.image_get %}
                                    <td class="cart__image-wrapper cart-flex-item">
                                        <a href="{{ post.get_absolute_url  }}"><img class="cart__image" src="{{ variable.image.url }}" alt="Elastic Waist Dress - Navy / Small"></a>
                                    </td>{% endwith %}
                                    <td class="cart__meta small--text-left cart-flex-item">
                                        <div class="list-view-item__title">
                                            <a href="{{ post.get_absolute_url }}">{{ post.name }} </a>
                                        </div>

                                        <div class="cart__meta-text">
                                            Размер: {{ post.size }}<br>
                                        </div>
                                    </td>
                                    <td class="cart__price-wrapper cart-flex-item">
                                        <span class="money">{{ items.price }}</span>
                                    </td>
                                    <td class="cart__update-wrapper cart-flex-item text-right">
                                        <div class="cart__qty text-center">
                                            <div class="qtyField">
                                                {{ items.quantity }}
                                            </div>
                                        </div>
                                    </td>
                                    <td class="text-right small--hide cart-price">
                                        <div><span class="money">{{ items.total_price }}</span></div>
                                    </td>
                                    <td class="text-center"><a href="{% url 'cart:cart_remove' post.id %}" class="btn btn--secondary cart__remove" title="Remove tem"><i class="icon icon anm anm-times-l"></i></a></td>
                                </tr>
                    {% endwith %}
                        {% endfor %}
                            </tbody>
                    		<tfoot>
                                <tr>
                                    <td colspan="3" class="text-left"><a href="/" class="btn--link cart-continue"><i class="icon icon-arrow-circle-left"></i> Продолжить покупки</a></td>
                                </tr>
                            </tfoot>
                    </table>


                    <hr>

                    </form>
               	</div>
                <div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
<!--                 	<div class="cart-note">
                    	<div class="solid-border">
							<h5><label for="CartSpecialInstructions" class="cart-note__label small--text-center">Примечание к вашему заказу</label></h5>
							<textarea name="note" id="CartSpecialInstructions" class="cart-note__input"></textarea>
						</div>
                    </div> -->
                    <div class="solid-border">
                      <div class="row">
                      	<span class="col-12 col-sm-6 cart__subtotal-title"><strong>Общая стоимость заказа</strong></span>
                        <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-right"><span class="money">{{ cart.get_total_price }}</span></span>
                      </div>


                        <a id="cartCheckout" class="btn btn--small-wide checkout" disabled="disabled" href="{% url 'orders:order_create' %}">Checkout</a>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <!--End Body Content-->
{% endblock %}