b_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from b_shop import settings
from shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

cart/urls.py
from django.urls import path, re_path

from . import views
from .views import *

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:post_id>', views.cart_add, name='cart_add'),
    path('remove/<int:post_id>', views.cart_remove, name='cart_remove'),
    ]

orders/urls.py
from django.urls import path, re_path

from . import views
from .views import *

urlpatterns = [
    path('create', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from shop.models import Item
from django.db.models.signals import post_save

class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None, verbose_name='название статуса')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Статус {}'.format(self.name)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    phone = models.CharField(max_length=48, verbose_name='Телефон')
    message = models.TextField(null=True,default=None, blank=True, verbose_name="Сообщение")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.ForeignKey(Status, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='статус')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return  'Заказ {0}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    post = models.ForeignKey(Item, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    # def get_cost(self):
    #     return self.price_per_item * self.quantity

    def save(self, *args, **kwargs):
        price_per_item = self.post.price
        self.price = price_per_item
        self.total_price = self.quantity * price_per_item

        super(OrderItem, self).save(*args, **kwargs)

def orderItem_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_items_in_order = OrderItem.objects.filter(order=order)

    order_total_price = 0
    for i in all_items_in_order:
        order_total_price += i.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)

post_save.connect(orderItem_post_save, sender=OrderItem)

orders/forms.py
from django import forms
from .models import Order
from django.utils.translation import gettext_lazy as _



class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        
        fields = ['first_name', 'phone', 'message']
        labels = {
            'first_name': _(''),
            'phone': _(''),
            'message': _(''),
        }
        help_texts = {
            'first_name': _(''),
            'phone': _(''),
            'message': _(''),
        }

        widgets = {
            'first_name': forms.TextInput
                           (attrs={'placeholder':'Ваше имя'}),
            'phone': forms.TextInput
                           (attrs={'placeholder':'Номер телефона'}),
            'message': forms.Textarea(attrs={'rows':4, 'cols':15, 'placeholder':'Сообщение'}), 
        }

orders/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         post=item['item'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            order_created(order.id, cart)
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                      {'cart': cart, 'form': form})

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}Счет{% endblock %}

{% block content %}
<!--Body Content-->
    <div id="page-content">
        <div class="bredcrumbWrap">
                    <div class="container breadcrumbs">
                         <a href="/" title="Back to the home page">Каталог</a><span aria-hidden="true">›</span><a href="{% url 'cart:cart_detail' %}" title="Back to the home page">Ваша корзина</a>›<span aria-hidden="true"></span><span>Заказ</span>
                    </div>
        </div>
         <div class="container">


            <div class="row billing-fields">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 sm-margin-30px-bottom">
                    <div class="create-ac-content bg-light-gray padding-20px-all">
                          <h2 class="login-title mb-3">Заполните форму для заказа</h2>
                        <form action=" " method="post" class="order-form"> {% csrf_token %}


                                 {{ form.as_p }}
                                     <div class="order-button-payment">
                                    <button class="btn" type="submit">Отправить</button>
                                </div>

                        </form>
                    </div>
                </div>

                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="your-order-payment">
                        <div class="your-order">
                            <h2 class="order-title mb-4">Ваш заказ</h2>
                            <div class="table-responsive-sm order-table">

                                <table class="bg-white table table-bordered table-hover text-center">
                                    <thead>
                                        <tr>
                                            <th class="text-left">Товар</th>
                                            <th>Цена</th>
                                            <th>Размер</th>
                                            <th>Количество</th>
                                            <th>Всего</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for items in cart %}
                                        {% with post=items.item %}
                                        <tr>
                                            <td class="text-left">{{ post.name }}</td>
                                            <td>{{ post.price }}</td>
                                            <td>{{ post.size }}</td>
                                            <td>{{ items.quantity }}</td>
                                            <td>{{ items.total_price }}</td>
                                        </tr>
                                        {% endwith %}
                                    {% endfor %}    
                                    </tbody>
                                    <tfoot class="font-weight-600">
                                        <tr>
                                            <td colspan="4" class="text-right">Итого</td>
                                            <td>{{cart.get_total_price }}</td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>

                        <hr />








                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}Заказ принят{% endblock %}

{% block content %}
<div class="container">
<div class="alert alert-success text-uppercase" style="margin-top: 3em; margin-bottom: 20em;" role="alert">
    <strong>Благодарим за заказ!</strong> Ожидайте звонка
</div>
<div colspan="3" class="text-left"><a href="/" class="btn--link cart-continue"><i class="icon icon-arrow-circle-left"></i> Продолжить покупки</a></div>
</div>
    
{% endblock %}