b_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from b_shop import settings
from shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

cart/urls.py
from django.urls import path, re_path

from . import views
from .views import *

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:post_id>', views.cart_add, name='cart_add'),
    path('remove/<int:post_id>', views.cart_remove, name='cart_remove'),
    ]

shop/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path('', item_list, name='home'),
    path('action/', action, name='action'),
    path('sale/', sale, name='sale'),
    path('contact/', contact, name='contact'),
    path('rental/', rental, name='rental'),
    path('category/wedding', wedding_dress, name='wedding'),
    path('category/evening', evening_dress, name='evening'),
    path('category/child', child_dress, name='child'),
    path('post/<slug:post_slug>/', item_detail, name='post'),
]

shop/models.py
from django.db import models
from django.urls import reverse

class StatusMessages(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None, verbose_name='статус сообщения')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Статус {}'.format(self.name)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class ItemCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name='название категории')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

class Item(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(blank=True, verbose_name="Описание")
    size = models.CharField(max_length=10, verbose_name="Размер")
    old_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=None, verbose_name='пред. цена')
    is_new = models.BooleanField(default=True, verbose_name="Новое")
    action = models.DecimalField(max_digits=4, decimal_places=0, default=None, blank=True, null=True, verbose_name='скидка %')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена')
    stock = models.PositiveIntegerField(verbose_name="запас на складе")
    category = models.ForeignKey(ItemCategory, on_delete=models.CASCADE, blank=True, null=True, default=None, verbose_name='категория')
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")


    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('shop:post', kwargs={'post_slug': self.slug})

    def image_get(self):
        return ItemImage.objects.get(itpm=self, is_main=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-time_create', 'name']
        index_together = (('id', 'slug'),)

class ItemImage(models.Model):
    itpm = models.ForeignKey(Item, blank=True, null=True,on_delete=models.CASCADE, default=True, related_name='itpm',)
    image = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото")
    is_main = models.BooleanField(default=False, verbose_name="Главная")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self):
        return '{}'.format(self.itpm.name)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

class Messages(models.Model):
    phone = models.CharField(max_length=48, verbose_name='Номер телефона')
    status = models.ForeignKey(StatusMessages, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='статус')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Телефон'
        verbose_name_plural = 'Телефоны'

    def __str__(self):
        return  'Телефон {0}'.format(self.phone)

class MessagesDetail(models.Model):
    name = models.CharField(max_length=55, verbose_name="Имя")
    phone = models.CharField(max_length=48, verbose_name='Телефон')
    message = models.TextField(verbose_name="Сообщение")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return  'Имя {0}'.format(self.name)

class Reviews(models.Model):
    image = models.ImageField(upload_to="reviews/%Y/%m/%d/", verbose_name="Фото отзыва")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")

    def __str__(self):
        return 'Отзыв {0}'.format(self.id)

    class Meta:

        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

shop/forms.py
from django import forms
from .models import Messages, MessagesDetail
from django.utils.translation import gettext_lazy as _

class MessagesForm(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ['phone']
        labels = {
            'phone': _(''),
        }
        help_texts = {
            'phone': _(''),
        }

        widgets = {
            'phone': forms.TextInput
                           (attrs={'placeholder':'Номер телефона'}),
        }

class MessagesDetailForm(forms.ModelForm):
    class Meta:
        model = MessagesDetail
        fields = ['name', 'phone', 'message']
        lables = {
            'name': _(''),
            'phone': _(''),
            'message': _('')
        }
        help_texts = {
            'name': _(''),
            'phone': _(''),
            'message': _('')
        }
        widgets = {
            'name': forms.TextInput
                    (attrs={'placeholder': 'Имя'}),
            'phone': forms.TextInput
                           (attrs={'placeholder':'Номер телефона'}),
            'message': forms.Textarea(attrs={'rows':4, 'cols':15, 'placeholder':'Сообщение'}),
                 
        }

shop/views.py
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from cart.forms import CartAddItemForm
from .models import *
from .forms import MessagesForm, MessagesDetailForm
from .tasks import call_request, message_detail

menu = [
    {'title': "Акции", 'url_name': 'action'},
    {'title': "Распродажа", 'url_name': 'sale'}, 
    {'title': "Условия проката", 'url_name': 'rental'},
    {'title': "Контакты", 'url_name': 'contact'},
]


def item_list(request):
    posts = Item.objects.filter(is_published=True)
    image_dress = ItemImage.objects.filter(is_published=True, is_main=True)
    item_wedd = image_dress.filter(itpm__category__id=1)
    item_evn = image_dress.filter(itpm__category__id=2)
    item_child = image_dress.filter(itpm__category__id=3)
    reviews = Reviews.objects.filter(is_published=True)
    form = MessagesForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form = form.save()
            call_request(form.id)
            return render(request, 'shop/item_list_message.html',)        
    
    context = {
        'posts': posts,
        'image_dress': image_dress,
        'item_child': item_child,
        'item_wedd': item_wedd,
        'item_evn': item_evn,
        'reviews': reviews,
        'menu': menu,
        'title': 'Каталог товаров',
        'form': form,
    }

    return render(request, 'shop/item_list.html', context=context)

def item_detail(request, post_slug):
    itpm = get_object_or_404(Item, slug=post_slug)
    photos = ItemImage.objects.filter(itpm=itpm, is_main=False)
    mainphoto = ItemImage.objects.filter(itpm=itpm, is_main=True)
    cart_product_form = CartAddItemForm()
    form_detail = MessagesDetailForm(request.POST or None)
    if request.method == 'POST':
        if form_detail.is_valid():
            form_detail = form_detail.save()
            message_detail(itpm.id, form_detail.id)
            return render(request, 'shop/detail_message.html',) 
    context = {
        'itpm': itpm,
        'photos': photos,
        'mainphoto': mainphoto,
        'menu': menu,
        'cart_product_form': cart_product_form,
        'title': itpm.name,
        'form_detail': form_detail,
    }

    return render(request, 'shop/detail.html', context=context)

def pageNotFound(request, exception):
    context = {
    'menu': menu,
    'title': 'Страница не найдена',
    }
    return render(request, 'shop/pagenotfound.html', context=context)

def sale(request):
    context = {
    'menu': menu,
    'title': 'Распродажа',
    }
    return render(request, 'shop/sale.html', context=context)


def action(request):
    posts = Item.objects.filter(is_published=True)
    image_dress = ItemImage.objects.filter(is_published=True, is_main=True)
    paginator = Paginator(image_dress, 8)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'posts': posts,
        'image_dress': image_dress,
        'menu': menu,
        'title': 'Товары по акции',
    }

    return render(request, 'shop/action.html', context=context)

def contact(request):
    context = {
    'menu': menu,
    'title': 'Контакты',
    }
    return render(request, 'shop/contact.html', context=context)

def rental(request):
    context = {
    'menu': menu,
    'title': 'Условия проката',
    }
    return render(request, 'shop/rental.html', context=context)

def wedding_dress(request):
    
    posts = Item.objects.filter(is_published=True)
    image_dress = ItemImage.objects.filter(is_published=True, is_main=True)
    item_wedd = image_dress.filter(itpm__category__id=1)
    paginator = Paginator(item_wedd, 8)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'posts': posts,
        'image_dress': image_dress,
        'item_wedd': item_wedd,
        'menu': menu,
        'title': 'Свадебные платья',
    }

    return render(request, 'shop/catalog/catalog1.html', context=context)

def evening_dress(request):
   
    posts = Item.objects.filter(is_published=True)
    image_dress = ItemImage.objects.filter(is_published=True, is_main=True)
    item_evn = image_dress.filter(itpm__category__id=2)
    paginator = Paginator(item_evn, 8)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'posts': posts,
        'image_dress': image_dress,
        'item_evn': item_evn,
        'menu': menu,
        'title': 'Вечерние платья',
    }

    return render(request, 'shop/catalog/catalog2.html', context=context)

def child_dress(request):
    
    posts = Item.objects.filter(is_published=True)
    image_dress = ItemImage.objects.filter(is_published=True, is_main=True)
    item_child = image_dress.filter(itpm__category__id=3)
    paginator = Paginator(item_child, 8)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'posts': posts,
        'image_dress': image_dress,
        'item_child': item_child,
        'menu': menu,
        'title': 'Детские платья',
    }

    return render(request, 'shop/catalog/catalog3.html', context=context)

shop/templates/shop/catalog/catalog1.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
   <!--Body Content--> 
<div class="d-flex justify-content-around" style="margin-bottom: 5px; margin-top: 3px;">
    <div class="container breadcrumbs" style="margin: 0; padding: 0; border 0;">
        <div class="collapse navbar-collapse d-flex justify-content-around" style="display: flex; justify-content: space-between;">
          <div class="d-flex justify-content-center">
            <input type="button" class="button-30" style=" box-shadow: #D6D6E7 0 3px 7px inset; transform: translateY(2px);" onclick="location.href='{% url 'shop:wedding' %}';" value="СВАДЕБНЫЕ">
            <input type="button" class="button-30" onclick="location.href='{% url 'shop:evening' %}';" value="ВЕЧЕРНИЕ">
            <input type="button" class="button-30" onclick="location.href='{% url 'shop:child' %}';" value="ДЕТСКИЕ">
          </div>  
         
        </div>
                    </div>
</div>





        <!--Home slider-->
<div id="page-content">
        <div class="collection-header">
            <div class="collection-hero">
                <div class="collection-hero__image"><img class="blur-up lazyload" data-src="{% static 'assets/images/cat-women2.jpg' %}" src="{% static 'assets/images/cat-women2.jpg' %}" alt="Women" title="Women" /></div>
                <div class="collection-hero__title-wrapper"><h1 class="collection-hero__title page-width">Shop Grid</h1></div>
            </div>
        </div>
        <div class="product-rows section">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="section-header text-center">
                            <h2 class="h2">Свадебные платья</h2>
                            <p>Grab these new items before they are gone!</p>
                        </div>
                    </div>
                </div>
                <div class="grid-products">
                    <div class="row">
                        {% for imd in page_obj %}
                     
                        
                       <div class="col-6 col-sm-2 col-md-3 col-lg-3 item">
                            <!-- start product image -->
                            <div class="product-image">
                                <!-- start product image -->
                                <a href="{{ imd.itpm.get_absolute_url }}" class="grid-view-item__link">
                                    <!-- image -->
                                    <img class="blur-up lazyload" data-src="{{ imd.image.url }}" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- End image -->
                                    <img class="grid-view-item__image hover variantImg" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- Variant Image--> 
                                    <!-- product label -->
                                    <div class="product-labels rounded">
                                        {% if imd.itpm.action %}
                                        <span class="lbl on-sale">- {{ imd.itpm.action }} %</span>
                                        {% endif %}
                                        {% if imd.itpm.is_new %}
                                        <span class="lbl pr-label1">Новое</span>
                                        {% endif %}
                                    </div>                                       
                                    <!-- End product label -->
                                </a>
                                <!-- end product image -->
                            </div>
                            <!-- end product image -->
                            <!--start product details -->
                            <div class="product-details text-center">
                                <!-- product name -->
                                <div class="product-name">
                                    <a href="product-layout-1.html">{{ imd.itpm.name }}</a>
                                </div>
                                <!-- End product name -->
                                <!-- product price -->
                                <div class="product-price">
                                    {% if imd.itpm.old_price %}
                                    <span class="old-price">{{ imd.itpm.old_price }}</span>
                                    {% endif %}
                                    <span class="price">{{ imd.itpm.price }}</span>
                                </div>
                                <!-- End product price -->
                            </div>
                            <!-- End product details -->
                        </div>
                    {% endfor %}
                    </div>
                    {% if page_obj.has_other_pages %}
                    <hr class="clear">
                    <div class="pagination">
                      <ul>
                        {% if page_obj.has_previous %}
                        <li class=""><a href="?page={{ page_obj.previous_page_number }}">&lt</a></li>
                        {% endif %}
                        {%for p in page_obj.paginator.page_range %}
                        {% if page_obj.number == p %}
                        <li class="active"><a href="?page={{ p }}">{{ p }}</a></li>
                        {% elif p >= page_obj.number|add:-3 and p <= page_obj.number|add:3 %}
                        <li class=""><a href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class=""><a href="?page={{ page_obj.next_page_number }}">&gt</a></li>
                        {% endif %}
                      </ul>
                    </div>
                    {% endif %}
                </div>
           </div>
        </div>
   
</div>
{% endblock %}

shop/templates/shop/catalog/catalog2.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
   <!--Body Content--> 
<div class="d-flex justify-content-around" style="margin-bottom: 5px; margin-top: 3px;">
    <div class="container breadcrumbs" style="margin: 0; padding: 0; border 0;">
        <div class="collapse navbar-collapse d-flex justify-content-around" style="display: flex; justify-content: space-between;">
          <div class="d-flex justify-content-center">
            <input type="button" class="button-30"  onclick="location.href='{% url 'shop:wedding' %}';" value="СВАДЕБНЫЕ">
            <input type="button" class="button-30" style=" box-shadow: #D6D6E7 0 3px 7px inset; transform: translateY(2px);" onclick="location.href='{% url 'shop:evening' %}';" value="ВЕЧЕРНИЕ">
            <input type="button" class="button-30" onclick="location.href='{% url 'shop:child' %}';" value="ДЕТСКИЕ">
          </div>  
         
        </div>
                    </div>
</div>





        <!--Home slider-->
<div id="page-content">
        <div class="collection-header">
            <div class="collection-hero">
                <div class="collection-hero__image"><img class="blur-up lazyload" data-src="{% static 'assets/images/cat-women2.jpg' %}" src="{% static 'assets/images/cat-women2.jpg' %}" alt="Women" title="Women" /></div>
                <div class="collection-hero__title-wrapper"><h1 class="collection-hero__title page-width">Shop Grid</h1></div>
            </div>
        </div>
        <div class="product-rows section">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="section-header text-center">
                            <h2 class="h2">Вечерние платья</h2>
                            <p>Grab these new items before they are gone!</p>
                        </div>
                    </div>
                </div>
                <div class="grid-products">
                    <div class="row">
                        {% for imd in page_obj %}
                     
                        <div class="col-6 col-sm-2 col-md-3 col-lg-3 item">
                            <!-- start product image -->
                            <div class="product-image">
                                <!-- start product image -->
                                <a href="{{ imd.itpm.get_absolute_url }}" class="grid-view-item__link">
                                    <!-- image -->
                                    <img class="blur-up lazyload" data-src="{{ imd.image.url }}" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- End image -->
                                    <img class="grid-view-item__image hover variantImg" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- Variant Image--> 
                                    <!-- product label -->
                                    <div class="product-labels rounded">
                                        {% if imd.itpm.action %}
                                        <span class="lbl on-sale">- {{ imd.itpm.action }} %</span>
                                        {% endif %}
                                        {% if imd.itpm.is_new %}
                                        <span class="lbl pr-label1">Новое</span>
                                        {% endif %}
                                    </div>                                       
                                    <!-- End product label -->
                                </a>
                                <!-- end product image -->
                            </div>
                            <!-- end product image -->
                            <!--start product details -->
                            <div class="product-details text-center">
                                <!-- product name -->
                                <div class="product-name">
                                    <a href="product-layout-1.html">{{ imd.itpm.name }}</a>
                                </div>
                                <!-- End product name -->
                                <!-- product price -->
                                <div class="product-price">
                                    {% if imd.itpm.old_price %}
                                    <span class="old-price">{{ imd.itpm.old_price }}</span>
                                    {% endif %}
                                    <span class="price">{{ imd.itpm.price }}</span>
                                </div>
                                <!-- End product price -->
                            </div>
                            <!-- End product details -->
                        </div>
                        
                    {% endfor %}
                    </div>
                    {% if page_obj.has_other_pages %}
                    <hr class="clear">
                    <div class="pagination">
                      <ul>
                        {% if page_obj.has_previous %}
                        <li class=""><a href="?page={{ page_obj.previous_page_number }}">&lt</a></li>
                        {% endif %}
                        {%for p in page_obj.paginator.page_range %}
                        {% if page_obj.number == p %}
                        <li class="active"><a href="?page={{ p }}">{{ p }}</a></li>
                        {% elif p >= page_obj.number|add:-3 and p <= page_obj.number|add:3 %}
                        <li class=""><a href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class=""><a href="?page={{ page_obj.next_page_number }}">&gt</a></li>
                        {% endif %}
                      </ul>
                    </div>
                    {% endif %}
                </div>
           </div>
        </div>
   
</div>
{% endblock %}

shop/templates/shop/catalog/catalog3.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
   <!--Body Content--> 
<div class="d-flex justify-content-around" style="margin-bottom: 5px; margin-top: 3px;">
    <div class="container breadcrumbs" style="margin: 0; padding: 0; border 0;">
        <div class="collapse navbar-collapse d-flex justify-content-around" style="display: flex; justify-content: space-between;">
          <div class="d-flex justify-content-center">
            <input type="button" class="button-30" onclick="location.href='{% url 'shop:wedding' %}';" value="СВАДЕБНЫЕ">
            <input type="button" class="button-30" onclick="location.href='{% url 'shop:evening' %}';" value="ВЕЧЕРНИЕ">
            <input type="button" class="button-30" style=" box-shadow: #D6D6E7 0 3px 7px inset; transform: translateY(2px);" onclick="location.href='{% url 'shop:child' %}';" value="ДЕТСКИЕ">
          </div>  
         
        </div>
                    </div>
</div>





        <!--Home slider-->
<div id="page-content">
        <div class="collection-header">
            <div class="collection-hero">
                <div class="collection-hero__image"><img class="blur-up lazyload" data-src="{% static 'assets/images/cat-women2.jpg' %}" src="{% static 'assets/images/cat-women2.jpg' %}" alt="Women" title="Women" /></div>
                <div class="collection-hero__title-wrapper"><h1 class="collection-hero__title page-width">Shop Grid</h1></div>
            </div>
        </div>
        <div class="product-rows section">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="section-header text-center">
                            <h2 class="h2">Детские платья</h2>
                            <p>Grab these new items before they are gone!</p>
                        </div>
                    </div>
                </div>
                <div class="grid-products">
                    <div class="row">
                        {% for imd in page_obj %}
                     
                        <div class="col-6 col-sm-2 col-md-3 col-lg-3 item">
                            <!-- start product image -->
                            <div class="product-image">
                                <!-- start product image -->
                                <a href="{{ imd.itpm.get_absolute_url }}" class="grid-view-item__link">
                                    <!-- image -->
                                    <img class="blur-up lazyload" data-src="{{ imd.image.url }}" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- End image -->
                                    <img class="grid-view-item__image hover variantImg" src="{{ imd.image.url }}" alt="image" title="product">
                                    <!-- Variant Image--> 
                                    <!-- product label -->
                                    <div class="product-labels rounded">
                                        {% if imd.itpm.action %}
                                        <span class="lbl on-sale">- {{ imd.itpm.action }} %</span>
                                        {% endif %}
                                        {% if imd.itpm.is_new %}
                                        <span class="lbl pr-label1">Новое</span>
                                        {% endif %}
                                    </div>                                       
                                    <!-- End product label -->
                                </a>
                                <!-- end product image -->
                            </div>
                            <!-- end product image -->
                            <!--start product details -->
                            <div class="product-details text-center">
                                <!-- product name -->
                                <div class="product-name">
                                    <a href="product-layout-1.html">{{ imd.itpm.name }}</a>
                                </div>
                                <!-- End product name -->
                                <!-- product price -->
                                <div class="product-price">
                                    {% if imd.itpm.old_price %}
                                    <span class="old-price">{{ imd.itpm.old_price }}</span>
                                    {% endif %}
                                    <span class="price">{{ imd.itpm.price }}</span>
                                </div>
                                <!-- End product price -->
                            </div>
                            <!-- End product details -->
                        </div>
                        
                    {% endfor %}
                    </div>
                    {% if page_obj.has_other_pages %}
                    <hr class="clear">
                    <div class="pagination">
                      <ul>
                        {% if page_obj.has_previous %}
                        <li class=""><a href="?page={{ page_obj.previous_page_number }}">&lt</a></li>
                        {% endif %}
                        {%for p in page_obj.paginator.page_range %}
                        {% if page_obj.number == p %}
                        <li class="active"><a href="?page={{ p }}">{{ p }}</a></li>
                        {% elif p >= page_obj.number|add:-3 and p <= page_obj.number|add:3 %}
                        <li class=""><a href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class=""><a href="?page={{ page_obj.next_page_number }}">&gt</a></li>
                        {% endif %}
                      </ul>
                    </div>
                    {% endif %}
                </div>
           </div>
        </div>
   
</div>
{% endblock %}